/**
 * Generate assets/manifest.json from the asset itself.   node tools/build.mjs [--check]
 *
 * WHY. Until 2026-08-28 the install skill verified the asset against numbers typed into English
 * prose - "≈ 987 KB, ≈ 5,300 lines", `buildStamp:"2026-08-18.1"`, "the ten read tools". Prose does
 * not change when the file does, so every release silently invalidated its own guard. By the time
 * WS36 shipped, SKILL.md was asserting a size, a line count, a build stamp AND a tool list that
 * were all wrong - a guard that fails on a CORRECT file, which teaches the installer to ignore it.
 * A guard that cries wolf is worse than no guard.
 *
 * Nobody types these numbers now. They are derived from the file, and the tool list is derived
 * from the build's own ARG_CONTRACT rather than from someone's memory of it - which is what made
 * the 1.0.2-skill-against-a-1.0.3-build failure ("no licences at all") possible.
 *
 *   node tools/build.mjs           regenerate manifest.json
 *   node tools/build.mjs --check   verify manifest matches the asset; non-zero exit if not (CI)
 */
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const ROOT     = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ASSET    = path.join(ROOT, 'skills/project-intelligence-dashboard/assets/dashboard.html');
const MANIFEST = path.join(ROOT, 'skills/project-intelligence-dashboard/assets/manifest.json');
const CHECK    = process.argv.includes('--check');

const buf = fs.readFileSync(ASSET);
const src = buf.toString('utf8');

const pick = (re, what) => {
  const m = re.exec(src);
  if (!m) { console.error('build: could not read ' + what + ' from the asset'); process.exit(2); }
  return m[1];
};

const buildStamp       = pick(/buildStamp:"([^"]+)"/, 'buildStamp');
const tcsVersion       = pick(/tcsVersion:"([^"]+)"/, 'tcsVersion');
const contractCaptured = pick(/const CONTRACT_CAPTURED="([^"]+)"/, 'CONTRACT_CAPTURED');
const readOnly         = /,readOnly:true,/.test(src);

/* Tool list comes from the build's own contract table, so it can never disagree with the code. */
const i = src.indexOf('const ARG_CONTRACT={');
const j = src.indexOf('};', i);
if (i < 0 || j < 0) { console.error('build: ARG_CONTRACT not found'); process.exit(2); }
const ARG_CONTRACT = new Function(src.slice(i, j + 2) + '\n;return ARG_CONTRACT;')();

/* Same predicate the shipped call() uses to decide read vs write - one definition, not two. */
const isWrite = t => /(update|create|delete|change|add|remove|invite|set|restore|reorder)_/.test(t);
const tools = Object.keys(ARG_CONTRACT).sort();
const read  = tools.filter(t => !isWrite(t));
const write = tools.filter(isWrite);

const manifest = {
  _comment: 'GENERATED by tools/build.mjs - do not hand-edit. Run `node tools/build.mjs` after any change to dashboard.html.',
  buildStamp, tcsVersion, readOnly, contractCaptured,
  asset: {
    file: 'dashboard.html',
    bytes: buf.length,
    lines: src.split('\n').length,
    sha256: crypto.createHash('sha256').update(buf).digest('hex')
  },
  tools: { read, write },
  generatedAt: new Date().toISOString().slice(0, 10)
};

if (CHECK) {
  if (!fs.existsSync(MANIFEST)) { console.error('build --check: manifest.json is missing. Run `node tools/build.mjs`.'); process.exit(1); }
  const have = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  const norm = o => JSON.stringify({ ...o, generatedAt: undefined });
  if (norm(have) !== norm(manifest)) {
    console.error('build --check: manifest.json is STALE - it does not describe the asset beside it.');
    console.error('  manifest says : ' + have.asset.bytes + ' bytes, ' + have.asset.lines + ' lines, build ' + have.buildStamp);
    console.error('  asset is      : ' + manifest.asset.bytes + ' bytes, ' + manifest.asset.lines + ' lines, build ' + manifest.buildStamp);
    console.error('  fix: node tools/build.mjs');
    process.exit(1);
  }
  console.log('manifest.json matches the asset  (build ' + buildStamp + ', ' + manifest.asset.bytes + ' bytes, sha256 ' + manifest.asset.sha256.slice(0, 12) + '…)');
  process.exit(0);
}

fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
console.log('wrote ' + path.relative(ROOT, MANIFEST));
console.log('  build      ' + buildStamp + '   terms v' + tcsVersion + '   readOnly=' + readOnly);
console.log('  asset      ' + manifest.asset.bytes + ' bytes, ' + manifest.asset.lines + ' lines');
console.log('  sha256     ' + manifest.asset.sha256);
console.log('  contract   captured ' + contractCaptured + '  (' + read.length + ' read, ' + write.length + ' write)');
